### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [BankoP/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You use some good techniques here and kept your code well organized. Take a look at the issues I created as they suggest some important changes that will help you as project increase in size. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by BankoP** [comment]
Thanks, I fixed everything. Now the code looks a lot better.
